name: ' Update AL-Go System Files'

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is https://github.com/freddydk/AL-Go@lowhanging)
        required: false
        default: ''
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  UpdateALGoSystemFiles:
    name: 'Update AL-Go System Files'
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Dump Workflow Information
        uses: freddydk/AL-Go/Actions/DumpWorkflowInfo@lowhanging
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@lowhanging
        with:
          shell: powershell
          eventId: "DO0098"

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@lowhanging
        with:
          shell: powershell
          get: templateUrl

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@lowhanging
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Override templateUrl
        env:
          templateUrl: ${{ github.event.inputs.templateUrl }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $templateUrl = $ENV:templateUrl
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "templateUrl=$templateUrl"
          }

      - name: Update AL-Go system files (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: freddydk/AL-Go/Actions/CheckForUpdates@lowhanging
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: ${{ github.event.inputs.downloadLatest }}
          update: 'Y'
          templateUrl: ${{ env.templateUrl }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Update AL-Go system files (scheduled trigger - try direct commit)
        if: github.event_name == 'schedule'
        continue-on-error: true
        uses: freddydk/AL-Go/Actions/CheckForUpdates@lowhanging
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: true
          update: 'Y'
          templateUrl: ${{ env.templateUrl }}
          directCommit: true

      - name: Update AL-Go system files (scheduled trigger - try pull request)
        if: env.UpdateStatus != 'Success' && github.event_name == 'schedule'
        uses: freddydk/AL-Go/Actions/CheckForUpdates@lowhanging
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: true
          update: 'Y'
          templateUrl: ${{ env.templateUrl }}
          directCommit: false

      - name: Report error
        if: env.UpdateStatus != 'Success'
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          Write-Host "::ERROR::$env:UpdateStatus"
          exit 1
  
      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@lowhanging
        with:
          shell: powershell
          eventId: "DO0098"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
